name: learning-actions
on: 
    pull_request:
        branches:
            - main 
        types: [closed]
jobs: 
    check-python-version:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - run: git checkout main
            - run: python -v
